# Generated by Django 5.0.4 on 2024-05-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='herb',
            name='season_in_pakistan',
        ),
        migrations.AddField(
            model_name='herb',
            name='season_in_pakistan',
            field=models.ManyToManyField(to='herb.month'),
        ),
    ]
