# Generated by Django 5.0.4 on 2024-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0002_month_remove_herb_season_in_pakistan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
