# Generated by Django 5.0.4 on 2024-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0003_herb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('soil_ph', models.FloatField()),
                ('nutrient_level', models.CharField(max_length=100)),
                ('texture', models.CharField(max_length=100)),
                ('organic_matter_content', models.CharField(max_length=100)),
            ],
        ),
    ]
