# Generated by Django 5.0.4 on 2024-06-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0006_herb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
