# Generated by Django 5.0.4 on 2024-06-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0007_alter_herb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='image',
        ),
    ]
