# Generated by Django 5.0.4 on 2024-06-28 18:24

import herb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0009_herb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=herb.models.plant_image_path),
        ),
    ]
