# Generated by Django 5.0.4 on 2024-07-02 18:31

import herb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0010_alter_herb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to=herb.models.plant_icons_path),
        ),
    ]
