# Generated by Django 5.0.4 on 2024-07-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0013_alter_herb_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='icons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
