# Generated by Django 5.0.4 on 2024-07-03 13:52

import django.db.models.deletion
import herb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0015_alter_herb_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('width', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GardenDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField()),
                ('column_no', models.IntegerField()),
                ('plant_name', models.CharField(max_length=255)),
                ('icons', models.ImageField(blank=True, null=True, upload_to=herb.models.plant_icons_path)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='herb.garden')),
            ],
        ),
    ]
