# Generated by Django 5.0.4 on 2024-07-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0020_gardendetail_garden'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardendetail',
            name='herb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herb.herb'),
        ),
    ]
