# Generated by Django 5.0.4 on 2024-07-04 07:27

import herb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0023_alter_herb_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to=herb.models.plant_icons_path),
        ),
    ]
