# Generated by Django 5.0.4 on 2024-07-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0032_alter_herb_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='garden_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
