# Generated by Django 5.0.4 on 2024-04-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usersubmittedimage_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
