# Generated by Django 5.0.4 on 2024-04-20 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(blank=True, default=False, null=True)),
                ('feedback_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
