# Generated by Django 5.0.4 on 2024-05-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_like_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
