# Generated by Django 5.0.4 on 2024-06-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_fcmtoken_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMToken',
        ),
    ]
